### PR TITLE
Introduce Match

### PR DESCRIPTION
**Pull request by mikearnaldi**

### CODE REVIEW

**Comment by jessekelly881** [comment]
Using a _with_ and a _not_ with a literal value does not seem to be marked as exhaustive. For example,

```js
const match = pipe(
  Match.type<number>(),
  Match.when(1, (_) => "a"),
  Match.not(1, (_) => "a"),
  Match.exaustive // Type error
)
```

**Comment by mikearnaldi** [comment]
> Using a _with_ and a _not_ with a literal value does not seem to be marked as exhaustive. For example,
> 
> ```js
> const match = pipe(
>   Match.type<number>(),
>   Match.when(1, (_) => "a"),
>   Match.not(1, (_) => "a"),
>   Match.exaustive // Type error
> )
> ```
> 
> Otherwise, this PR looks awesome! I'm super excited for this to be merged.

Not sure it will end up in schema probably if this gets through it will be it's own library I've just placed it here while we were exploring given it depends on schema (similar strategy to the Arbitrary module that will be extracted out)

**Comment by tim-smart** [comment]
> Using a _with_ and a _not_ with a literal value does not seem to be marked as exhaustive. For example,
> 
> ```js
> const match = pipe(
>   Match.type<number>(),
>   Match.when(1, (_) => "a"),
>   Match.not(1, (_) => "a"),
>   Match.exaustive // Type error
> )
> ```
> 
> Otherwise, this PR looks awesome! I'm super excited for this to be merged.

Hmm will need to think about that one some more, as `Exclude<number, 1>` reduces to `number`.

**Comment by tim-smart** [comment]
> Using a _with_ and a _not_ with a literal value does not seem to be marked as exhaustive. For example,
> 
> ```js
> const match = pipe(
>   Match.type<number>(),
>   Match.when(1, (_) => "a"),
>   Match.not(1, (_) => "a"),
>   Match.exaustive // Type error
> )
> ```
> 
> Otherwise, this PR looks awesome! I'm super excited for this to be merged.

Resolved here: https://github.com/fp-ts/schema/pull/60/files

**Comment by jessekelly881** [comment]
> > Using a _with_ and a _not_ with a literal value does not seem to be marked as exhaustive. For example,
> > ```js
> > const match = pipe(
> >   Match.type<number>(),
> >   Match.when(1, (_) => "a"),
> >   Match.not(1, (_) => "a"),
> >   Match.exaustive // Type error
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Otherwise, this PR looks awesome! I'm super excited for this to be merged.
> 
> Resolved here: https://github.com/fp-ts/schema/pull/60/files

Oh cool! Is it possible to add add predicates as well? https://github.com/gvergnaud/ts-pattern#Pwhen-patterns

**Comment by tim-smart** [comment]
@jessekelly881 I'll look at adding predicates soon.

Will need to work out the inference a bit more.

**Comment by jessekelly881** [comment]
Why the choice to move this to the effect org  instead of the @fp-ts org out of curiosity? This seems deeply integrated with fp-ts and not very specific to effect.

**Comment by mikearnaldi** [comment]
It will need to depend on types from both fp-ts and effect for the unify functionality and given also /data is getting moved to effect it kind of make sense having it here and fp-ts wants a closed scope core/optic/schema

**Pull request closed without merging**
