### PR TITLE
feat: added filter/multipleOf

### PR DESCRIPTION
**Pull request by jessekelly881**
Add multipleOf for numeric multiplicity. Closes issue #38

### CODE REVIEW

**Comment by jessekelly881** [comment]
The json schema specification specifies that the multipleOf parameter should be a positive number with up to 2 decimal places of precision. How do you think we should handle this?

**Comment by gcanti** [comment]
There's a comment in the stackoverflow answer talking about negative numbers and a small change to the `floatSafeRemainder` function, maybe it's a good idea to add tests for negative and fractional numbers as well

**Comment by jessekelly881** [comment]
Ah. Good point! I updated it. How should we handle the json schema issue btw? https://awwright.github.io/json-schema-org-pages/keyword/multipleOf

**Comment by gcanti** [comment]
> How should we handle the json schema issue btw?

What do you mean?

**Comment by jessekelly881** [comment]
According to the json schema spec the value of multipleOf should be a positive(non-zero) number of at most 2 digits. E.g. -1 or 0.001 are both invalid.

**Comment by gcanti** [comment]
IMO if our schema really works even with `0.0001`, it's a feature we can keep, it's up to a potential JSON Schema compiler to point out that some values are not valid for its specific purpose. 

In general, /schema is capable of performing more validations than JSON Schema and it is perfectly acceptable, we don't necessarily have to follow what JSON Schema does, just make sure that a potential JSON Schema compiler has the ability to understand what it needs to do (and potentially refuse to do it for its own reasons)

**Comment by jessekelly881** [comment]
Makes sense. Also, as a side note, I feel this remainder function might be a useful addition to @fp-ts/data/Number instead of inlining it here.

**Comment by gcanti** [comment]
Thanks @jessekelly881 !

**Pull request merged**
